version: '2'

services:
  php-apache:
      build: ./apache
      ports:
        - 8000:80 
      volumes:
        - ./php/:/var/www/
      environment:
        APACHE_RUN_USER: "#1000"
      links:
        - 'mariadb'
      depends_on: 
        - mariadb

  mariadb:
      image: mariadb:10.4
      volumes:
        - ./mysql-data/:/var/lib/mysql
      environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        MYSQL_ROOT_PASSWORD: 'root'
        MYSQL_USER: 'dev_user'
        MYSQL_PASSWORD: 'dev_password'
        MYSQL_DATABASE: 'dev_db'
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8001:80'
    environment:
      PMA_HOST: 'mariadb'
      MYSQL_ROOT_PASSWORD: 'root'
    links:
      - 'mariadb'
    depends_on:
      - mariadb
